# Generated by Django 5.2.7 on 2025-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
    ]
