# Generated by Django 5.2.7 on 2025-11-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AddField(
            model_name="tasktag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_tags",
                to="tags.tag",
                verbose_name="标签",
            ),
        ),
        migrations.AddField(
            model_name="tasktag",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_tags",
                to="tasks.task",
                verbose_name="任务",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="tasktag",
            unique_together={("task", "tag")},
        ),
    ]
