# Generated by Django 5.2.7 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
    ]
